name: elections-models
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz>=0.9
  - black
  - bokeh
  - fiona
  - geopandas
  - jupyterlab
  - libblas=*=*mkl
  - lxml
  - matplotlib
  - mkl-service
  - numpy
  - openpyxl
  - pandas
  - pip
  - pymc3>=3.9
  - python>=3.7
  - python-graphviz
  - scipy
  - shapely
  - theano>=1.0.5
  - voila
  - watermark
  - xarray
  - xlrd
  - pip:
    - black_nbconvert