name: elections-models
channels:
  - conda-forge
dependencies:
  - arviz
  - black
  - bokeh
  - fiona
  - geopandas
  - jupyterlab
  - libblas=*=*mkl
  - lxml
  - matplotlib
  - mkl-service
  - numpy
  - openpyxl
  - pandas
  - pip
  - pymc3
  - python-graphviz
  - scipy
  - shapely
  - voila
  - watermark
  - xarray
  - xlrd